language: objective-c
osx_image: xcode7.1
before_install:
  - export LANG=en_US.UTF-8
  - bundle install
  - pod install
script: xcodebuild -workspace IGHTMLQuery.xcworkspace -scheme IGHTMLQuery -sdk iphonesimulator test | xcpretty -c; exit ${PIPESTATUS[0]}
